<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('locations')->truncate();

        $locations = [
            // Remote option
            ['city' => 'Remote', 'country' => 'Remote', 'region' => 'Remote'],

            // Albania
            ['city' => 'Tirana', 'country' => 'Albania', 'region' => 'Tirana'],
            ['city' => 'Durrës', 'country' => 'Albania', 'region' => 'Durrës'],
            ['city' => 'Vlorë', 'country' => 'Albania', 'region' => 'Vlorë'],
            ['city' => 'Elbasan', 'country' => 'Albania', 'region' => 'Elbasan'],
            ['city' => 'Shkodër', 'country' => 'Albania', 'region' => 'Shkodër'],
            ['city' => 'Fier', 'country' => 'Albania', 'region' => 'Fier'],
            ['city' => 'Korçë', 'country' => 'Albania', 'region' => 'Korçë'],
            ['city' => 'Berat', 'country' => 'Albania', 'region' => 'Berat'],
            ['city' => 'Lushnjë', 'country' => 'Albania', 'region' => 'Lushnjë'],
            ['city' => 'Kavajë', 'country' => 'Albania', 'region' => 'Kavajë'],

            // Austria
            ['city' => 'Vienna', 'country' => 'Austria', 'region' => 'Vienna'],
            ['city' => 'Graz', 'country' => 'Austria', 'region' => 'Styria'],
            ['city' => 'Linz', 'country' => 'Austria', 'region' => 'Upper Austria'],
            ['city' => 'Salzburg', 'country' => 'Austria', 'region' => 'Salzburg'],
            ['city' => 'Innsbruck', 'country' => 'Austria', 'region' => 'Tyrol'],
            ['city' => 'Klagenfurt', 'country' => 'Austria', 'region' => 'Carinthia'],
            ['city' => 'Villach', 'country' => 'Austria', 'region' => 'Carinthia'],
            ['city' => 'Wels', 'country' => 'Austria', 'region' => 'Upper Austria'],
            ['city' => 'Sankt Pölten', 'country' => 'Austria', 'region' => 'Lower Austria'],
            ['city' => 'Dornbirn', 'country' => 'Austria', 'region' => 'Vorarlberg'],
            ['city' => 'Wiener Neustadt', 'country' => 'Austria', 'region' => 'Lower Austria'],
            ['city' => 'Steyr', 'country' => 'Austria', 'region' => 'Upper Austria'],
            ['city' => 'Feldkirch', 'country' => 'Austria', 'region' => 'Vorarlberg'],
            ['city' => 'Bregenz', 'country' => 'Austria', 'region' => 'Vorarlberg'],
            ['city' => 'Wolfsberg', 'country' => 'Austria', 'region' => 'Carinthia'],

            // Belgium
            ['city' => 'Brussels', 'country' => 'Belgium', 'region' => 'Brussels-Capital'],
            ['city' => 'Antwerp', 'country' => 'Belgium', 'region' => 'Flanders'],
            ['city' => 'Ghent', 'country' => 'Belgium', 'region' => 'Flanders'],
            ['city' => 'Charleroi', 'country' => 'Belgium', 'region' => 'Wallonia'],
            ['city' => 'Liège', 'country' => 'Belgium', 'region' => 'Wallonia'],
            ['city' => 'Bruges', 'country' => 'Belgium', 'region' => 'Flanders'],
            ['city' => 'Namur', 'country' => 'Belgium', 'region' => 'Wallonia'],
            ['city' => 'Leuven', 'country' => 'Belgium', 'region' => 'Flanders'],
            ['city' => 'Mons', 'country' => 'Belgium', 'region' => 'Wallonia'],
            ['city' => 'Aalst', 'country' => 'Belgium', 'region' => 'Flanders'],
            ['city' => 'Mechelen', 'country' => 'Belgium', 'region' => 'Flanders'],
            ['city' => 'La Louvière', 'country' => 'Belgium', 'region' => 'Wallonia'],
            ['city' => 'Hasselt', 'country' => 'Belgium', 'region' => 'Flanders'],
            ['city' => 'Kortrijk', 'country' => 'Belgium', 'region' => 'Flanders'],
            ['city' => 'Sint-Niklaas', 'country' => 'Belgium', 'region' => 'Flanders'],

            // Bulgaria
            ['city' => 'Sofia', 'country' => 'Bulgaria', 'region' => 'Sofia City'],
            ['city' => 'Plovdiv', 'country' => 'Bulgaria', 'region' => 'Plovdiv'],
            ['city' => 'Varna', 'country' => 'Bulgaria', 'region' => 'Varna'],
            ['city' => 'Burgas', 'country' => 'Bulgaria', 'region' => 'Burgas'],
            ['city' => 'Ruse', 'country' => 'Bulgaria', 'region' => 'Ruse'],
            ['city' => 'Stara Zagora', 'country' => 'Bulgaria', 'region' => 'Stara Zagora'],
            ['city' => 'Pleven', 'country' => 'Bulgaria', 'region' => 'Pleven'],
            ['city' => 'Sliven', 'country' => 'Bulgaria', 'region' => 'Sliven'],
            ['city' => 'Dobrich', 'country' => 'Bulgaria', 'region' => 'Dobrich'],
            ['city' => 'Shumen', 'country' => 'Bulgaria', 'region' => 'Shumen'],
            ['city' => 'Pernik', 'country' => 'Bulgaria', 'region' => 'Pernik'],
            ['city' => 'Haskovo', 'country' => 'Bulgaria', 'region' => 'Haskovo'],
            ['city' => 'Yambol', 'country' => 'Bulgaria', 'region' => 'Yambol'],
            ['city' => 'Pazardzhik', 'country' => 'Bulgaria', 'region' => 'Pazardzhik'],
            ['city' => 'Blagoevgrad', 'country' => 'Bulgaria', 'region' => 'Blagoevgrad'],

            // Croatia
            ['city' => 'Zagreb', 'country' => 'Croatia', 'region' => 'Zagreb'],
            ['city' => 'Split', 'country' => 'Croatia', 'region' => 'Split-Dalmatia'],
            ['city' => 'Rijeka', 'country' => 'Croatia', 'region' => 'Primorje-Gorski Kotar'],
            ['city' => 'Osijek', 'country' => 'Croatia', 'region' => 'Osijek-Baranja'],
            ['city' => 'Zadar', 'country' => 'Croatia', 'region' => 'Zadar'],
            ['city' => 'Velika Gorica', 'country' => 'Croatia', 'region' => 'Zagreb County'],
            ['city' => 'Slavonski Brod', 'country' => 'Croatia', 'region' => 'Brod-Posavina'],
            ['city' => 'Pula', 'country' => 'Croatia', 'region' => 'Istria'],
            ['city' => 'Karlovac', 'country' => 'Croatia', 'region' => 'Karlovac'],
            ['city' => 'Sisak', 'country' => 'Croatia', 'region' => 'Sisak-Moslavina'],
            ['city' => 'Varaždin', 'country' => 'Croatia', 'region' => 'Varaždin'],
            ['city' => 'Šibenik', 'country' => 'Croatia', 'region' => 'Šibenik-Knin'],
            ['city' => 'Dubrovnik', 'country' => 'Croatia', 'region' => 'Dubrovnik-Neretva'],
            ['city' => 'Bjelovar', 'country' => 'Croatia', 'region' => 'Bjelovar-Bilogora'],
            ['city' => 'Kaštela', 'country' => 'Croatia', 'region' => 'Split-Dalmatia'],

            // Czech Republic
            ['city' => 'Prague', 'country' => 'Czech Republic', 'region' => 'Prague'],
            ['city' => 'Brno', 'country' => 'Czech Republic', 'region' => 'South Moravian'],
            ['city' => 'Ostrava', 'country' => 'Czech Republic', 'region' => 'Moravian-Silesian'],
            ['city' => 'Plzeň', 'country' => 'Czech Republic', 'region' => 'Plzeň'],
            ['city' => 'Liberec', 'country' => 'Czech Republic', 'region' => 'Liberec'],
            ['city' => 'Olomouc', 'country' => 'Czech Republic', 'region' => 'Olomouc'],
            ['city' => 'České Budějovice', 'country' => 'Czech Republic', 'region' => 'South Bohemian'],
            ['city' => 'Hradec Králové', 'country' => 'Czech Republic', 'region' => 'Hradec Králové'],
            ['city' => 'Ústí nad Labem', 'country' => 'Czech Republic', 'region' => 'Ústí nad Labem'],
            ['city' => 'Pardubice', 'country' => 'Czech Republic', 'region' => 'Pardubice'],
            ['city' => 'Zlín', 'country' => 'Czech Republic', 'region' => 'Zlín'],
            ['city' => 'Havířov', 'country' => 'Czech Republic', 'region' => 'Moravian-Silesian'],
            ['city' => 'Kladno', 'country' => 'Czech Republic', 'region' => 'Central Bohemian'],
            ['city' => 'Most', 'country' => 'Czech Republic', 'region' => 'Ústí nad Labem'],
            ['city' => 'Opava', 'country' => 'Czech Republic', 'region' => 'Moravian-Silesian'],

            // Denmark
            ['city' => 'Copenhagen', 'country' => 'Denmark', 'region' => 'Capital Region'],
            ['city' => 'Aarhus', 'country' => 'Denmark', 'region' => 'Central Denmark'],
            ['city' => 'Odense', 'country' => 'Denmark', 'region' => 'Southern Denmark'],
            ['city' => 'Aalborg', 'country' => 'Denmark', 'region' => 'North Denmark'],
            ['city' => 'Frederiksberg', 'country' => 'Denmark', 'region' => 'Capital Region'],
            ['city' => 'Esbjerg', 'country' => 'Denmark', 'region' => 'Southern Denmark'],
            ['city' => 'Gentofte', 'country' => 'Denmark', 'region' => 'Capital Region'],
            ['city' => 'Gladsaxe', 'country' => 'Denmark', 'region' => 'Capital Region'],
            ['city' => 'Randers', 'country' => 'Denmark', 'region' => 'Central Denmark'],
            ['city' => 'Kolding', 'country' => 'Denmark', 'region' => 'Southern Denmark'],
            ['city' => 'Horsens', 'country' => 'Denmark', 'region' => 'Central Denmark'],
            ['city' => 'Lyngby-Taarbæk', 'country' => 'Denmark', 'region' => 'Capital Region'],
            ['city' => 'Vejle', 'country' => 'Denmark', 'region' => 'Southern Denmark'],
            ['city' => 'Hvidovre', 'country' => 'Denmark', 'region' => 'Capital Region'],
            ['city' => 'Roskilde', 'country' => 'Denmark', 'region' => 'Zealand'],

            // Estonia
            ['city' => 'Tallinn', 'country' => 'Estonia', 'region' => 'Harju'],
            ['city' => 'Tartu', 'country' => 'Estonia', 'region' => 'Tartu'],
            ['city' => 'Narva', 'country' => 'Estonia', 'region' => 'Ida-Viru'],
            ['city' => 'Pärnu', 'country' => 'Estonia', 'region' => 'Pärnu'],
            ['city' => 'Kohtla-Järve', 'country' => 'Estonia', 'region' => 'Ida-Viru'],
            ['city' => 'Viljandi', 'country' => 'Estonia', 'region' => 'Viljandi'],
            ['city' => 'Rakvere', 'country' => 'Estonia', 'region' => 'Lääne-Viru'],
            ['city' => 'Maardu', 'country' => 'Estonia', 'region' => 'Harju'],
            ['city' => 'Kuressaare', 'country' => 'Estonia', 'region' => 'Saare'],
            ['city' => 'Sillamäe', 'country' => 'Estonia', 'region' => 'Ida-Viru'],
            ['city' => 'Võru', 'country' => 'Estonia', 'region' => 'Võru'],
            ['city' => 'Valga', 'country' => 'Estonia', 'region' => 'Valga'],
            ['city' => 'Haapsalu', 'country' => 'Estonia', 'region' => 'Lääne'],
            ['city' => 'Jõhvi', 'country' => 'Estonia', 'region' => 'Ida-Viru'],
            ['city' => 'Paide', 'country' => 'Estonia', 'region' => 'Järva'],

            // Finland
            ['city' => 'Helsinki', 'country' => 'Finland', 'region' => 'Uusimaa'],
            ['city' => 'Espoo', 'country' => 'Finland', 'region' => 'Uusimaa'],
            ['city' => 'Tampere', 'country' => 'Finland', 'region' => 'Pirkanmaa'],
            ['city' => 'Vantaa', 'country' => 'Finland', 'region' => 'Uusimaa'],
            ['city' => 'Oulu', 'country' => 'Finland', 'region' => 'North Ostrobothnia'],
            ['city' => 'Turku', 'country' => 'Finland', 'region' => 'Southwest Finland'],
            ['city' => 'Jyväskylä', 'country' => 'Finland', 'region' => 'Central Finland'],
            ['city' => 'Lahti', 'country' => 'Finland', 'region' => 'Päijänne Tavastia'],
            ['city' => 'Kuopio', 'country' => 'Finland', 'region' => 'Northern Savonia'],
            ['city' => 'Pori', 'country' => 'Finland', 'region' => 'Satakunta'],
            ['city' => 'Kouvola', 'country' => 'Finland', 'region' => 'Kymenlaakso'],
            ['city' => 'Joensuu', 'country' => 'Finland', 'region' => 'North Karelia'],
            ['city' => 'Lappeenranta', 'country' => 'Finland', 'region' => 'South Karelia'],
            ['city' => 'Hämeenlinna', 'country' => 'Finland', 'region' => 'Tavastia Proper'],
            ['city' => 'Vaasa', 'country' => 'Finland', 'region' => 'Ostrobothnia'],

            // France
            ['city' => 'Paris', 'country' => 'France', 'region' => 'Île-de-France'],
            ['city' => 'Marseille', 'country' => 'France', 'region' => 'Provence-Alpes-Côte d\'Azur'],
            ['city' => 'Lyon', 'country' => 'France', 'region' => 'Auvergne-Rhône-Alpes'],
            ['city' => 'Toulouse', 'country' => 'France', 'region' => 'Occitanie'],
            ['city' => 'Nice', 'country' => 'France', 'region' => 'Provence-Alpes-Côte d\'Azur'],
            ['city' => 'Nantes', 'country' => 'France', 'region' => 'Pays de la Loire'],
            ['city' => 'Montpellier', 'country' => 'France', 'region' => 'Occitanie'],
            ['city' => 'Strasbourg', 'country' => 'France', 'region' => 'Grand Est'],
            ['city' => 'Bordeaux', 'country' => 'France', 'region' => 'Nouvelle-Aquitaine'],
            ['city' => 'Lille', 'country' => 'France', 'region' => 'Hauts-de-France'],
            ['city' => 'Rennes', 'country' => 'France', 'region' => 'Brittany'],
            ['city' => 'Reims', 'country' => 'France', 'region' => 'Grand Est'],
            ['city' => 'Le Havre', 'country' => 'France', 'region' => 'Normandy'],
            ['city' => 'Saint-Étienne', 'country' => 'France', 'region' => 'Auvergne-Rhône-Alpes'],
            ['city' => 'Toulon', 'country' => 'France', 'region' => 'Provence-Alpes-Côte d\'Azur'],

            // Germany
            ['city' => 'Berlin', 'country' => 'Germany', 'region' => 'Berlin'],
            ['city' => 'Hamburg', 'country' => 'Germany', 'region' => 'Hamburg'],
            ['city' => 'Munich', 'country' => 'Germany', 'region' => 'Bavaria'],
            ['city' => 'Cologne', 'country' => 'Germany', 'region' => 'North Rhine-Westphalia'],
            ['city' => 'Frankfurt', 'country' => 'Germany', 'region' => 'Hesse'],
            ['city' => 'Stuttgart', 'country' => 'Germany', 'region' => 'Baden-Württemberg'],
            ['city' => 'Düsseldorf', 'country' => 'Germany', 'region' => 'North Rhine-Westphalia'],
            ['city' => 'Leipzig', 'country' => 'Germany', 'region' => 'Saxony'],
            ['city' => 'Dortmund', 'country' => 'Germany', 'region' => 'North Rhine-Westphalia'],
            ['city' => 'Essen', 'country' => 'Germany', 'region' => 'North Rhine-Westphalia'],
            ['city' => 'Bremen', 'country' => 'Germany', 'region' => 'Bremen'],
            ['city' => 'Dresden', 'country' => 'Germany', 'region' => 'Saxony'],
            ['city' => 'Hanover', 'country' => 'Germany', 'region' => 'Lower Saxony'],
            ['city' => 'Nuremberg', 'country' => 'Germany', 'region' => 'Bavaria'],
            ['city' => 'Duisburg', 'country' => 'Germany', 'region' => 'North Rhine-Westphalia'],

            // Greece
            ['city' => 'Athens', 'country' => 'Greece', 'region' => 'Attica'],
            ['city' => 'Thessaloniki', 'country' => 'Greece', 'region' => 'Central Macedonia'],
            ['city' => 'Patras', 'country' => 'Greece', 'region' => 'Western Greece'],
            ['city' => 'Heraklion', 'country' => 'Greece', 'region' => 'Crete'],
            ['city' => 'Larissa', 'country' => 'Greece', 'region' => 'Thessaly'],
            ['city' => 'Volos', 'country' => 'Greece', 'region' => 'Thessaly'],
            ['city' => 'Rhodes', 'country' => 'Greece', 'region' => 'South Aegean'],
            ['city' => 'Ioannina', 'country' => 'Greece', 'region' => 'Epirus'],
            ['city' => 'Chania', 'country' => 'Greece', 'region' => 'Crete'],
            ['city' => 'Chalcis', 'country' => 'Greece', 'region' => 'Central Greece'],
            ['city' => 'Agrinio', 'country' => 'Greece', 'region' => 'Western Greece'],
            ['city' => 'Katerini', 'country' => 'Greece', 'region' => 'Central Macedonia'],
            ['city' => 'Trikala', 'country' => 'Greece', 'region' => 'Thessaly'],
            ['city' => 'Serres', 'country' => 'Greece', 'region' => 'Central Macedonia'],
            ['city' => 'Lamia', 'country' => 'Greece', 'region' => 'Central Greece'],

            // Hungary
            ['city' => 'Budapest', 'country' => 'Hungary', 'region' => 'Central Hungary'],
            ['city' => 'Debrecen', 'country' => 'Hungary', 'region' => 'Northern Great Plain'],
            ['city' => 'Szeged', 'country' => 'Hungary', 'region' => 'Southern Great Plain'],
            ['city' => 'Miskolc', 'country' => 'Hungary', 'region' => 'Northern Hungary'],
            ['city' => 'Pécs', 'country' => 'Hungary', 'region' => 'Southern Transdanubia'],
            ['city' => 'Győr', 'country' => 'Hungary', 'region' => 'Western Transdanubia'],
            ['city' => 'Nyíregyháza', 'country' => 'Hungary', 'region' => 'Northern Great Plain'],
            ['city' => 'Kecskemét', 'country' => 'Hungary', 'region' => 'Southern Great Plain'],
            ['city' => 'Székesfehérvár', 'country' => 'Hungary', 'region' => 'Central Transdanubia'],
            ['city' => 'Szombathely', 'country' => 'Hungary', 'region' => 'Western Transdanubia'],
            ['city' => 'Szolnok', 'country' => 'Hungary', 'region' => 'Northern Great Plain'],
            ['city' => 'Érd', 'country' => 'Hungary', 'region' => 'Central Hungary'],
            ['city' => 'Tatabánya', 'country' => 'Hungary', 'region' => 'Central Transdanubia'],
            ['city' => 'Sopron', 'country' => 'Hungary', 'region' => 'Western Transdanubia'],
            ['city' => 'Kaposvár', 'country' => 'Hungary', 'region' => 'Southern Transdanubia'],

            // Ireland
            ['city' => 'Dublin', 'country' => 'Ireland', 'region' => 'Leinster'],
            ['city' => 'Cork', 'country' => 'Ireland', 'region' => 'Munster'],
            ['city' => 'Limerick', 'country' => 'Ireland', 'region' => 'Munster'],
            ['city' => 'Galway', 'country' => 'Ireland', 'region' => 'Connacht'],
            ['city' => 'Waterford', 'country' => 'Ireland', 'region' => 'Munster'],
            ['city' => 'Drogheda', 'country' => 'Ireland', 'region' => 'Leinster'],
            ['city' => 'Swords', 'country' => 'Ireland', 'region' => 'Leinster'],
            ['city' => 'Dundalk', 'country' => 'Ireland', 'region' => 'Leinster'],
            ['city' => 'Bray', 'country' => 'Ireland', 'region' => 'Leinster'],
            ['city' => 'Navan', 'country' => 'Ireland', 'region' => 'Leinster'],
            ['city' => 'Kilkenny', 'country' => 'Ireland', 'region' => 'Leinster'],
            ['city' => 'Ennis', 'country' => 'Ireland', 'region' => 'Munster'],
            ['city' => 'Carlow', 'country' => 'Ireland', 'region' => 'Leinster'],
            ['city' => 'Tralee', 'country' => 'Ireland', 'region' => 'Munster'],
            ['city' => 'Newbridge', 'country' => 'Ireland', 'region' => 'Leinster'],

            // Italy
            ['city' => 'Rome', 'country' => 'Italy', 'region' => 'Lazio'],
            ['city' => 'Milan', 'country' => 'Italy', 'region' => 'Lombardy'],
            ['city' => 'Naples', 'country' => 'Italy', 'region' => 'Campania'],
            ['city' => 'Turin', 'country' => 'Italy', 'region' => 'Piedmont'],
            ['city' => 'Palermo', 'country' => 'Italy', 'region' => 'Sicily'],
            ['city' => 'Genoa', 'country' => 'Italy', 'region' => 'Liguria'],
            ['city' => 'Bologna', 'country' => 'Italy', 'region' => 'Emilia-Romagna'],
            ['city' => 'Florence', 'country' => 'Italy', 'region' => 'Tuscany'],
            ['city' => 'Bari', 'country' => 'Italy', 'region' => 'Apulia'],
            ['city' => 'Catania', 'country' => 'Italy', 'region' => 'Sicily'],
            ['city' => 'Venice', 'country' => 'Italy', 'region' => 'Veneto'],
            ['city' => 'Verona', 'country' => 'Italy', 'region' => 'Veneto'],
            ['city' => 'Messina', 'country' => 'Italy', 'region' => 'Sicily'],
            ['city' => 'Padua', 'country' => 'Italy', 'region' => 'Veneto'],
            ['city' => 'Trieste', 'country' => 'Italy', 'region' => 'Friuli-Venezia Giulia'],

            // Latvia
            ['city' => 'Riga', 'country' => 'Latvia', 'region' => 'Riga'],
            ['city' => 'Daugavpils', 'country' => 'Latvia', 'region' => 'Latgale'],
            ['city' => 'Liepāja', 'country' => 'Latvia', 'region' => 'Courland'],
            ['city' => 'Jelgava', 'country' => 'Latvia', 'region' => 'Semigallia'],
            ['city' => 'Jūrmala', 'country' => 'Latvia', 'region' => 'Riga'],
            ['city' => 'Ventspils', 'country' => 'Latvia', 'region' => 'Courland'],
            ['city' => 'Rēzekne', 'country' => 'Latvia', 'region' => 'Latgale'],
            ['city' => 'Valmiera', 'country' => 'Latvia', 'region' => 'Vidzeme'],
            ['city' => 'Jēkabpils', 'country' => 'Latvia', 'region' => 'Selonia'],
            ['city' => 'Ogre', 'country' => 'Latvia', 'region' => 'Vidzeme'],
            ['city' => 'Salaspils', 'country' => 'Latvia', 'region' => 'Vidzeme'],
            ['city' => 'Tukums', 'country' => 'Latvia', 'region' => 'Courland'],
            ['city' => 'Cēsis', 'country' => 'Latvia', 'region' => 'Vidzeme'],
            ['city' => 'Sigulda', 'country' => 'Latvia', 'region' => 'Vidzeme'],
            ['city' => 'Olaine', 'country' => 'Latvia', 'region' => 'Vidzeme'],

            // Lithuania
            ['city' => 'Vilnius', 'country' => 'Lithuania', 'region' => 'Vilnius'],
            ['city' => 'Kaunas', 'country' => 'Lithuania', 'region' => 'Kaunas'],
            ['city' => 'Klaipėda', 'country' => 'Lithuania', 'region' => 'Klaipėda'],
            ['city' => 'Šiauliai', 'country' => 'Lithuania', 'region' => 'Šiauliai'],
            ['city' => 'Panevėžys', 'country' => 'Lithuania', 'region' => 'Panevėžys'],
            ['city' => 'Alytus', 'country' => 'Lithuania', 'region' => 'Alytus'],
            ['city' => 'Marijampolė', 'country' => 'Lithuania', 'region' => 'Marijampolė'],
            ['city' => 'Mažeikiai', 'country' => 'Lithuania', 'region' => 'Telšiai'],
            ['city' => 'Jonava', 'country' => 'Lithuania', 'region' => 'Kaunas'],
            ['city' => 'Utena', 'country' => 'Lithuania', 'region' => 'Utena'],
            ['city' => 'Kėdainiai', 'country' => 'Lithuania', 'region' => 'Kaunas'],
            ['city' => 'Telšiai', 'country' => 'Lithuania', 'region' => 'Telšiai'],
            ['city' => 'Visaginas', 'country' => 'Lithuania', 'region' => 'Utena'],
            ['city' => 'Tauragė', 'country' => 'Lithuania', 'region' => 'Tauragė'],
            ['city' => 'Ukmergė', 'country' => 'Lithuania', 'region' => 'Vilnius'],

            // Netherlands
            ['city' => 'Amsterdam', 'country' => 'Netherlands', 'region' => 'North Holland'],
            ['city' => 'Rotterdam', 'country' => 'Netherlands', 'region' => 'South Holland'],
            ['city' => 'The Hague', 'country' => 'Netherlands', 'region' => 'South Holland'],
            ['city' => 'Utrecht', 'country' => 'Netherlands', 'region' => 'Utrecht'],
            ['city' => 'Eindhoven', 'country' => 'Netherlands', 'region' => 'North Brabant'],
            ['city' => 'Tilburg', 'country' => 'Netherlands', 'region' => 'North Brabant'],
            ['city' => 'Almere', 'country' => 'Netherlands', 'region' => 'Flevoland'],
            ['city' => 'Groningen', 'country' => 'Netherlands', 'region' => 'Groningen'],
            ['city' => 'Breda', 'country' => 'Netherlands', 'region' => 'North Brabant'],
            ['city' => 'Nijmegen', 'country' => 'Netherlands', 'region' => 'Gelderland'],
            ['city' => 'Apeldoorn', 'country' => 'Netherlands', 'region' => 'Gelderland'],
            ['city' => 'Enschede', 'country' => 'Netherlands', 'region' => 'Overijssel'],
            ['city' => 'Haarlem', 'country' => 'Netherlands', 'region' => 'North Holland'],
            ['city' => 'Arnhem', 'country' => 'Netherlands', 'region' => 'Gelderland'],
            ['city' => 'Amersfoort', 'country' => 'Netherlands', 'region' => 'Utrecht'],

            // Norway
            ['city' => 'Oslo', 'country' => 'Norway', 'region' => 'Oslo'],
            ['city' => 'Bergen', 'country' => 'Norway', 'region' => 'Vestland'],
            ['city' => 'Trondheim', 'country' => 'Norway', 'region' => 'Trøndelag'],
            ['city' => 'Stavanger', 'country' => 'Norway', 'region' => 'Rogaland'],
            ['city' => 'Bærum', 'country' => 'Norway', 'region' => 'Viken'],
            ['city' => 'Kristiansand', 'country' => 'Norway', 'region' => 'Agder'],
            ['city' => 'Drammen', 'country' => 'Norway', 'region' => 'Viken'],
            ['city' => 'Asker', 'country' => 'Norway', 'region' => 'Viken'],
            ['city' => 'Lillestrøm', 'country' => 'Norway', 'region' => 'Viken'],
            ['city' => 'Fredrikstad', 'country' => 'Norway', 'region' => 'Viken'],
            ['city' => 'Sandnes', 'country' => 'Norway', 'region' => 'Rogaland'],
            ['city' => 'Tromsø', 'country' => 'Norway', 'region' => 'Troms og Finnmark'],
            ['city' => 'Sandefjord', 'country' => 'Norway', 'region' => 'Vestfold og Telemark'],
            ['city' => 'Nordre Follo', 'country' => 'Norway', 'region' => 'Viken'],
            ['city' => 'Sarpsborg', 'country' => 'Norway', 'region' => 'Viken'],

            // Poland
            ['city' => 'Warsaw', 'country' => 'Poland', 'region' => 'Mazovia'],
            ['city' => 'Krakow', 'country' => 'Poland', 'region' => 'Lesser Poland'],
            ['city' => 'Lodz', 'country' => 'Poland', 'region' => 'Lodz Voivodeship'],
            ['city' => 'Wroclaw', 'country' => 'Poland', 'region' => 'Lower Silesia'],
            ['city' => 'Poznan', 'country' => 'Poland', 'region' => 'Greater Poland'],
            ['city' => 'Gdansk', 'country' => 'Poland', 'region' => 'Pomerania'],
            ['city' => 'Szczecin', 'country' => 'Poland', 'region' => 'West Pomerania'],
            ['city' => 'Bydgoszcz', 'country' => 'Poland', 'region' => 'Kuyavian-Pomerania'],
            ['city' => 'Lublin', 'country' => 'Poland', 'region' => 'Lublin Voivodeship'],
            ['city' => 'Bialystok', 'country' => 'Poland', 'region' => 'Podlaskie'],
            ['city' => 'Katowice', 'country' => 'Poland', 'region' => 'Silesia'],
            ['city' => 'Gdynia', 'country' => 'Poland', 'region' => 'Pomerania'],
            ['city' => 'Czestochowa', 'country' => 'Poland', 'region' => 'Silesia'],
            ['city' => 'Radom', 'country' => 'Poland', 'region' => 'Mazovia'],
            ['city' => 'Sosnowiec', 'country' => 'Poland', 'region' => 'Silesia'],

            // Portugal
            ['city' => 'Lisbon', 'country' => 'Portugal', 'region' => 'Lisbon District'],
            ['city' => 'Porto', 'country' => 'Portugal', 'region' => 'Porto District'],
            ['city' => 'Vila Nova de Gaia', 'country' => 'Portugal', 'region' => 'Porto District'],
            ['city' => 'Amadora', 'country' => 'Portugal', 'region' => 'Lisbon District'],
            ['city' => 'Braga', 'country' => 'Portugal', 'region' => 'Braga District'],
            ['city' => 'Funchal', 'country' => 'Portugal', 'region' => 'Madeira'],
            ['city' => 'Coimbra', 'country' => 'Portugal', 'region' => 'Coimbra District'],
            ['city' => 'Setúbal', 'country' => 'Portugal', 'region' => 'Setúbal District'],
            ['city' => 'Agualva-Cacém', 'country' => 'Portugal', 'region' => 'Lisbon District'],
            ['city' => 'Queluz', 'country' => 'Portugal', 'region' => 'Lisbon District'],
            ['city' => 'Aveiro', 'country' => 'Portugal', 'region' => 'Aveiro District'],
            ['city' => 'Guimarães', 'country' => 'Portugal', 'region' => 'Braga District'],
            ['city' => 'Odivelas', 'country' => 'Portugal', 'region' => 'Lisbon District'],
            ['city' => 'Rio Tinto', 'country' => 'Portugal', 'region' => 'Porto District'],
            ['city' => 'Viseu', 'country' => 'Portugal', 'region' => 'Viseu District'],

            // Romania
            ['city' => 'Bucharest', 'country' => 'Romania', 'region' => 'Bucharest'],
            ['city' => 'Cluj-Napoca', 'country' => 'Romania', 'region' => 'Cluj'],
            ['city' => 'Timișoara', 'country' => 'Romania', 'region' => 'Timiș'],
            ['city' => 'Iași', 'country' => 'Romania', 'region' => 'Iași'],
            ['city' => 'Constanța', 'country' => 'Romania', 'region' => 'Constanța'],
            ['city' => 'Craiova', 'country' => 'Romania', 'region' => 'Dolj'],
            ['city' => 'Brașov', 'country' => 'Romania', 'region' => 'Brașov'],
            ['city' => 'Galați', 'country' => 'Romania', 'region' => 'Galați'],
            ['city' => 'Ploiești', 'country' => 'Romania', 'region' => 'Prahova'],
            ['city' => 'Oradea', 'country' => 'Romania', 'region' => 'Bihor'],
            ['city' => 'Brăila', 'country' => 'Romania', 'region' => 'Brăila'],
            ['city' => 'Arad', 'country' => 'Romania', 'region' => 'Arad'],
            ['city' => 'Pitești', 'country' => 'Romania', 'region' => 'Argeș'],
            ['city' => 'Sibiu', 'country' => 'Romania', 'region' => 'Sibiu'],
            ['city' => 'Bacău', 'country' => 'Romania', 'region' => 'Bacău'],

            // Spain
            ['city' => 'Madrid', 'country' => 'Spain', 'region' => 'Madrid'],
            ['city' => 'Barcelona', 'country' => 'Spain', 'region' => 'Catalonia'],
            ['city' => 'Valencia', 'country' => 'Spain', 'region' => 'Valencia'],
            ['city' => 'Seville', 'country' => 'Spain', 'region' => 'Andalusia'],
            ['city' => 'Zaragoza', 'country' => 'Spain', 'region' => 'Aragon'],
            ['city' => 'Málaga', 'country' => 'Spain', 'region' => 'Andalusia'],
            ['city' => 'Murcia', 'country' => 'Spain', 'region' => 'Murcia'],
            ['city' => 'Palma', 'country' => 'Spain', 'region' => 'Balearic Islands'],
            ['city' => 'Las Palmas', 'country' => 'Spain', 'region' => 'Canary Islands'],
            ['city' => 'Bilbao', 'country' => 'Spain', 'region' => 'Basque Country'],
            ['city' => 'Alicante', 'country' => 'Spain', 'region' => 'Valencia'],
            ['city' => 'Córdoba', 'country' => 'Spain', 'region' => 'Andalusia'],
            ['city' => 'Valladolid', 'country' => 'Spain', 'region' => 'Castile and León'],
            ['city' => 'Vigo', 'country' => 'Spain', 'region' => 'Galicia'],
            ['city' => 'Gijón', 'country' => 'Spain', 'region' => 'Asturias'],

            // Sweden
            ['city' => 'Stockholm', 'country' => 'Sweden', 'region' => 'Stockholm'],
            ['city' => 'Gothenburg', 'country' => 'Sweden', 'region' => 'Västra Götaland'],
            ['city' => 'Malmö', 'country' => 'Sweden', 'region' => 'Skåne'],
            ['city' => 'Uppsala', 'country' => 'Sweden', 'region' => 'Uppsala'],
            ['city' => 'Linköping', 'country' => 'Sweden', 'region' => 'Östergötland'],
            ['city' => 'Örebro', 'country' => 'Sweden', 'region' => 'Örebro'],
            ['city' => 'Västerås', 'country' => 'Sweden', 'region' => 'Västmanland'],
            ['city' => 'Helsingborg', 'country' => 'Sweden', 'region' => 'Skåne'],
            ['city' => 'Norrköping', 'country' => 'Sweden', 'region' => 'Östergötland'],
            ['city' => 'Jönköping', 'country' => 'Sweden', 'region' => 'Jönköping'],
            ['city' => 'Lund', 'country' => 'Sweden', 'region' => 'Skåne'],
            ['city' => 'Umeå', 'country' => 'Sweden', 'region' => 'Västerbotten'],
            ['city' => 'Gävle', 'country' => 'Sweden', 'region' => 'Gävleborg'],
            ['city' => 'Borås', 'country' => 'Sweden', 'region' => 'Västra Götaland'],
            ['city' => 'Södertälje', 'country' => 'Sweden', 'region' => 'Stockholm'],

            // Switzerland
            ['city' => 'Zurich', 'country' => 'Switzerland', 'region' => 'Zurich'],
            ['city' => 'Geneva', 'country' => 'Switzerland', 'region' => 'Geneva'],
            ['city' => 'Basel', 'country' => 'Switzerland', 'region' => 'Basel-Stadt'],
            ['city' => 'Lausanne', 'country' => 'Switzerland', 'region' => 'Vaud'],
            ['city' => 'Bern', 'country' => 'Switzerland', 'region' => 'Bern'],
            ['city' => 'Winterthur', 'country' => 'Switzerland', 'region' => 'Zurich'],
            ['city' => 'Lucerne', 'country' => 'Switzerland', 'region' => 'Lucerne'],
            ['city' => 'St. Gallen', 'country' => 'Switzerland', 'region' => 'St. Gallen'],
            ['city' => 'Lugano', 'country' => 'Switzerland', 'region' => 'Ticino'],
            ['city' => 'Biel/Bienne', 'country' => 'Switzerland', 'region' => 'Bern'],
            ['city' => 'Thun', 'country' => 'Switzerland', 'region' => 'Bern'],
            ['city' => 'Köniz', 'country' => 'Switzerland', 'region' => 'Bern'],
            ['city' => 'La Chaux-de-Fonds', 'country' => 'Switzerland', 'region' => 'Neuchâtel'],
            ['city' => 'Fribourg', 'country' => 'Switzerland', 'region' => 'Fribourg'],
            ['city' => 'Schaffhausen', 'country' => 'Switzerland', 'region' => 'Schaffhausen'],

            // Ukraine
            ['city' => 'Kyiv', 'country' => 'Ukraine', 'region' => 'Kyiv'],
            ['city' => 'Kharkiv', 'country' => 'Ukraine', 'region' => 'Kharkiv'],
            ['city' => 'Odesa', 'country' => 'Ukraine', 'region' => 'Odesa'],
            ['city' => 'Dnipro', 'country' => 'Ukraine', 'region' => 'Dnipropetrovsk'],
            ['city' => 'Donetsk', 'country' => 'Ukraine', 'region' => 'Donetsk'],
            ['city' => 'Zaporizhzhia', 'country' => 'Ukraine', 'region' => 'Zaporizhzhia'],
            ['city' => 'Lviv', 'country' => 'Ukraine', 'region' => 'Lviv'],
            ['city' => 'Kryvyi Rih', 'country' => 'Ukraine', 'region' => 'Dnipropetrovsk'],
            ['city' => 'Mykolaiv', 'country' => 'Ukraine', 'region' => 'Mykolaiv'],
            ['city' => 'Mariupol', 'country' => 'Ukraine', 'region' => 'Donetsk'],
            ['city' => 'Luhansk', 'country' => 'Ukraine', 'region' => 'Luhansk'],
            ['city' => 'Vinnytsia', 'country' => 'Ukraine', 'region' => 'Vinnytsia'],
            ['city' => 'Makiivka', 'country' => 'Ukraine', 'region' => 'Donetsk'],
            ['city' => 'Sevastopol', 'country' => 'Ukraine', 'region' => 'Crimea'],
            ['city' => 'Simferopol', 'country' => 'Ukraine', 'region' => 'Crimea'],

            // United Kingdom
            ['city' => 'London', 'country' => 'United Kingdom', 'region' => 'England'],
            ['city' => 'Birmingham', 'country' => 'United Kingdom', 'region' => 'England'],
            ['city' => 'Glasgow', 'country' => 'United Kingdom', 'region' => 'Scotland'],
            ['city' => 'Liverpool', 'country' => 'United Kingdom', 'region' => 'England'],
            ['city' => 'Bristol', 'country' => 'United Kingdom', 'region' => 'England'],
            ['city' => 'Manchester', 'country' => 'United Kingdom', 'region' => 'England'],
            ['city' => 'Sheffield', 'country' => 'United Kingdom', 'region' => 'England'],
            ['city' => 'Leeds', 'country' => 'United Kingdom', 'region' => 'England'],
            ['city' => 'Edinburgh', 'country' => 'United Kingdom', 'region' => 'Scotland'],
            ['city' => 'Leicester', 'country' => 'United Kingdom', 'region' => 'England'],
            ['city' => 'Coventry', 'country' => 'United Kingdom', 'region' => 'England'],
            ['city' => 'Bradford', 'country' => 'United Kingdom', 'region' => 'England'],
            ['city' => 'Cardiff', 'country' => 'United Kingdom', 'region' => 'Wales'],
            ['city' => 'Belfast', 'country' => 'United Kingdom', 'region' => 'Northern Ireland'],
            ['city' => 'Nottingham', 'country' => 'United Kingdom', 'region' => 'England'],
        ];

        DB::table('locations')->insert($locations);
    }
}
