<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Skill;

class SkillSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $skills = [
            // Languages
            'PHP',
            'Python',
            'JavaScript',
            'Java',
            'C#',
            'C++',
            'Ruby',
            'Go',
            'Swift',
            'Kotlin',
            'TypeScript',
            'Rust',
            'SQL',
            'HTML',
            'CSS',
            'Sass',
            'Less',
            'R',
            'MATLAB',
            'Scala',
            'Perl',
            'Haskell',
            'Lua',
            'Dart',
            'Objective-C',
            'Visual Basic',
            'Assembly',
            'C',
            'Delphi',

            // Web Frontend
            'React',
            'Angular',
            'Vue.js',
            'Next.js',
            'Nuxt.js',
            'Svelte',
            'Ember.js',
            'Backbone.js',
            'Redux',
            'MobX',
            'Tailwind CSS',
            'Bootstrap',
            'Foundation',
            'Material UI',
            'Ant Design',
            'Webpack',
            'Vite',
            'Babel',
            'JQuery',
            'WebAssembly',
            'Three.js',
            'Canvas API',
            'SVG',

            // Web Backend
            'Laravel',
            'Symfony',
            'Node.js',
            'Express.js',
            'NestJS',
            'Django',
            'Flask',
            'FastAPI',
            'Spring Boot',
            'ASP.NET Core',
            'Ruby on Rails',
            'Go Gin',
            'Phoenix',
            'Koa',
            'Fastify',
            'GraphQL',
            'Apollo',
            'REST API',
            'gRPC',
            'WebSockets',
            'Microservices',

            // Mobile
            'React Native',
            'Flutter',
            'Ionic',
            'Xamarin',
            'SwiftUI',
            'Jetpack Compose',
            'NativeScript',
            'Android SDK',
            'iOS SDK',
            'Mobile App Design',

            // Databases & Storage
            'MySQL',
            'PostgreSQL',
            'SQLite',
            'MongoDB',
            'Redis',
            'Oracle',
            'SQL Server',
            'MariaDB',
            'Cassandra',
            'DynamoDB',
            'Elasticsearch',
            'Solr',
            'Neo4j',
            'InfluxDB',
            'Firebase Realtime Database',
            'Firestore',
            'Realm',
            'ClickHouse',
            'Snowflake',
            'Memcached',

            // DevOps & Cloud
            'Git',
            'GitHub',
            'GitLab',
            'Bitbucket',
            'Docker',
            'Kubernetes',
            'Helm',
            'Terraform',
            'Ansible',
            'Puppet',
            'Chef',
            'Jenkins',
            'GitHub Actions',
            'GitLab CI',
            'CircleCI',
            'Travis CI',
            'AWS',
            'Azure',
            'Google Cloud Platform',
            'DigitalOcean',
            'Heroku',
            'Netlify',
            'Vercel',
            'Linux',
            'Ubuntu',
            'CentOS',
            'Debian',
            'Bash',
            'PowerShell',
            'Nginx',
            'Apache',
            'Varnish',
            'Prometheus',
            'Grafana',
            'ELK Stack',
            'New Relic',
            'Datadog',

            // Data Science & AI
            'TensorFlow',
            'PyTorch',
            'Keras',
            'Scikit-learn',
            'Pandas',
            'NumPy',
            'SciPy',
            'Matplotlib',
            'Seaborn',
            'OpenCV',
            'NLTK',
            'Spacy',
            'Hugging Face',
            'Large Language Models (LLM)',
            'Prompt Engineering',
            'LangChain',
            'OpenAI API',
            'Apache Spark',
            'Apache Kafka',
            'Hadoop',
            'Tableau',
            'Power BI',
            'Google Data Studio',

            // Security
            'Penetration Testing',
            'Ethical Hacking',
            'Cybersecurity',
            'OWASP Top 10',
            'Information Security',
            'Encryption',
            'Cryptography',
            'OAuth2',
            'JWT',
            'SAML',
            'SSO',
            'Identity Management',
            'Firewalls',
            'IDS/IPS',
            'Identity & Access Management (IAM)',

            // Testing & QA
            'Jest',
            'Mocha',
            'Chai',
            'Cypress',
            'Playwright',
            'Puppeteer',
            'Selenium',
            'PHPUnit',
            'Pytest',
            'JUnit',
            'Test-Driven Development (TDD)',
            'Behavior-Driven Development (BDD)',
            'Unit Testing',
            'Integration Testing',
            'End-to-End Testing',
            'Load Testing',

            // Software Design & Architecture
            'Design Patterns',
            'SOLID Principles',
            'Object-Oriented Programming (OOP)',
            'Functional Programming',
            'Domain-Driven Design (DDD)',
            'Service-Oriented Architecture (SOA)',
            'Event-Driven Architecture',
            'Serverless',
            'Clean Architecture',

            // Collaboration & PM
            'Agile',
            'Scrum',
            'Kanban',
            'Lean',
            'Jira',
            'Confluence',
            'Trello',
            'Asana',
            'Slack',
            'Microsoft Teams',
            'Project Management',
            'Product Management',
            'Product Design',

            // Design & Media
            'UI/UX Design',
            'Figma',
            'Adobe XD',
            'Sketch',
            'Photoshop',
            'Illustrator',
            'After Effects',
            'Premiere Pro',
            'Video Editing',
            '3D Modeling',
            'Blender',
            'Unity',
            'Unreal Engine',

            // Soft Skills
            'Communication',
            'Teamwork',
            'Problem Solving',
            'Critical Thinking',
            'Time Management',
            'Leadership',
            'Adaptability',
            'Creativity',
            'Emotional Intelligence',
            'Technical Writing',
            'Mentoring',
            'Public Speaking',
            'Conflict Resolution',
            'Decision Making',

            // Sales & Marketing
            'CRM',
            'SEO',
            'SEM',
            'Content Marketing',
            'Social Media Management',
            'B2B Sales',
            'B2C Sales',
            'Market Research',
            'Branding',
            'Copywriting',
            'Sales Prospecting',
            'Negotiation',
            'Public Relations',
            'Growth Hacking',
            'Email Marketing',
            'Influencer Marketing',
            'Sales Management',

            // Finance & Accounting
            'Financial Analysis',
            'Bookkeeping',
            'Auditing',
            'Tax Compliance',
            'IFRS',
            'GAAP',
            'Financial Modeling',
            'Budgeting',
            'Risk Management',
            'Payroll',
            'Accounts Payable',
            'Accounts Receivable',
            'QuickBooks',
            'Xero',
            'SAP ERP',
            'Banking Operations',
            'Investment Management',

            // Healthcare & Pharmacy
            'Nursing',
            'Patient Care',
            'Medical Terminology',
            'First Aid',
            'CPR',
            'Pharmacy',
            'Phlebotomy',
            'Diagnosis',
            'Medical Coding',
            'Telemedicine',
            'Health Informatics',
            'Clinical Research',
            'Rehabilitation',
            'Pediatrics',
            'Surgical Assistance',
            'Dentistry',

            // Engineering & Construction
            'AutoCAD',
            'Revit',
            'SolidWorks',
            'Civil Engineering',
            'Mechanical Engineering',
            'Electrical Engineering',
            'Structural Analysis',
            'Project Scheduling',
            'Blueprints',
            'Safety Management (HSE)',
            'Surveying',
            'Building Codes',
            'BIM',
            'HVAC',
            'Manufacturing Processes',

            // Logistics & Supply Chain
            'Inventory Management',
            'Warehouse Operations',
            'Supply Chain Optimization',
            'Procurement',
            'Freight Forwarding',
            'Distribution',
            'Demand Planning',
            'Six Sigma',
            'Lean Manufacturing',
            'Fleet Management',
            'Import/Export Compliance',
            'Last-Mile Delivery',

            // Education & Training
            'Curriculum Development',
            'Classroom Management',
            'E-learning',
            'Special Education',
            'Tutoring',
            'Educational Assessment',
            'Instructional Design',
            'Pedagogical Skills',
            'Early Childhood Education',
            'Academic Advising',
            'Corporate Training',

            // Hospitality & Tourism
            'Event Planning',
            'Hotel Management',
            'Food Safety',
            'Concierge Services',
            'Travel Planning',
            'Culinary Arts',
            'Mixology',
            'Catering',
            'Tourism Management',
            'Front Desk Operations',
            'Customer Experience Management',

            // Human Resources
            'Recruitment',
            'Employee Relations',
            'Talent Acquisition',
            'Performance Management',
            'Onboarding',
            'Labor Law',
            'Strategic HR',
            'Benefits Administration',
            'Diversity & Inclusion (D&I)',
            'Training & Development',
            'HRIS Systems',

            // Legal
            'Litigation',
            'Legal Research',
            'Contract Drafting',
            'Corporate Law',
            'Intellectual Property',
            'Compliance',
            'Mediation',
            'Criminal Law',
            'Family Law',
            'Employment Law',
            'International Law',

            // Customer Service & Admin
            'Customer Support',
            'Call Center Operations',
            'Office Administration',
            'Data Entry',
            'Secretarial Skills',
            'Translation',
            'Interpretation',
            'Quality Control',
            'Receptionist Skills',
            'Retail Sales',
            'Cashiering'
        ];

        foreach ($skills as $skill) {
            Skill::firstOrCreate(['name' => $skill]);
        }
    }
}
